### ISSUE TITLE
win binary pls

### ISSUE THREAD

**Issue by necros2k7** [cloudinary/fuif#2]
subj

**Comment by necros2k7** [comment]
Yes not only me I guess, compiled win binary of FUIF

**Comment by TheJaredWilcurt** [comment]
It would be nice if there were tagged releases on the GitHub Releases page that came with attached binaries for common platforms (Win32, OSX64, Lin32, Lin64).

* https://github.com/cloudinary/fuif/releases

This allows for other tooling to be built around FUIF with less friction as there is a trusted source to get the binaries from and they don't need to be manually built by people that aren't familiar with the build environment/programming languages used by FUIF development. It would also be helpful if the file names for the attachments on the releases followed a specific naming pattern so they could be downloaded programmatically from the GitHub API. Example:

* https://github.com/sass/node-sass/releases

**Comment by jonsneyers** [comment]
It would be premature to build tooling around FUIF since it is only a research prototype at this point. FUIF is going to be part of JPEG XL, and at some point it will have a stable bitstream and a reference implementation around which tooling can be built. But at this point it is too early for that.

**Comment by vrubleg** [comment]
@jonsneyers oh, it will be released as "JPEG XL"? It could be nice to mention it on the main page of the repository.

**Comment by jonsneyers** [comment]
Updated the main page. Thanks for the suggestion!
