### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by DonaldTsang** [cloudinary/fuif#4]
It would be good to use FUIF as a flexible thumbnail for http://hydrusnetwork.github.io/hydrus/

**Comment by DonaldTsang** [comment]
@roeeba made this https://github.com/python-pillow/Pillow/issues/3962

**Comment by roeeba** [comment]
Hi @DonaldTsang, Apologies for the late reply. 
Thanks sharing the code. I'll pass it on to our engineers to review.

**Comment by jonsneyers** [comment]
FUIF development has stopped since FUIF is subsumed in JPEG XL (https://jpeg.org/jpegxl/index.html), which is based on a combination of Pik and FUIF. Once the JPEG XL standard is ready, we are planning to make a royalty-free and open source reference implementation available.
