### ISSUE TITLE
Media Coverage and Adoption roadmap

### ISSUE THREAD

**Issue by DonaldTsang** [cloudinary/fuif#7]
Would like to know a few things that could affect the future of FUIF:
- Adoption by Browsers
    - Chrome and Chromium based browsers including Opera, Edge and Vivaldi
    - Firefox and Firefox forks
- Adoption by Operating System's default image viewers
    - Windows Photo Viewer
    - OSX Peview
    - Linux Eye of Gnome/MATE, Gwenview
    - Imagemagick, FFMPEG, GraphicsMagick
- Adoption by Professional artistic software
    - Photoshop and Illustrator
    - Affinity Photo and Affinity Designer
    - Krita, Inkscape and GIMP
    - Others possibly including Paint Tool Sai, Clip Studio, Fire Alpaca, MediaBang Paint, Photopea, Inkscape, BOxySVG, Figma etc. 
- Tech-related news coverage
- Social media coverage

**Comment by DonaldTsang** [comment]
@idobarnoam please check

**Comment by DonaldTsang** [comment]
Maybe collaboration with https://github.com/google/pik ?

**Comment by jonsneyers** [comment]
We are collaborating with the Pik team. In fact, JPEG XL (https://jpeg.org/jpegxl/index.html) is based on a combination of Pik and FUIF.

**Comment by DonaldTsang** [comment]
@jonsneyers holy crap so that is the "official" FUIF/PIK replacement?

**Comment by jonsneyers** [comment]
JPEG XL is currently being developed on a private gitlab repo that only JPEG committee members can access. We are aiming at a public release (and probably moving further development to a public github repo) by the end of the year.

**Comment by DonaldTsang** [comment]
@jonsneyers okay, so what license is it planning to release it on? It should be Open Source, and be either patent-free or patent-compliant in format, if this needs to thrive and gain adoption quickly. At the end it should not die like the other JPEG-* formats (I hope).

**Comment by jonsneyers** [comment]
Once the JPEG XL standard is ready, we are planning to make a royalty-free and open source reference implementation available. The license will likely be Apache 2.0.
