### ISSUE TITLE
Contacts

### ISSUE THREAD

**Issue by DonaldTsang** [cloudinary/fuif#8]
It would be much preferable if there is a way of contacting developers through one of these platforms:
- Discord (recommended)
- Email
- IRC
- Matrix
If you are available @idobarnoam please take a look

**Comment by TheJaredWilcurt** [comment]
+1 for Discord

**Comment by jonsneyers** [comment]
You can contact me through twitter (@jonsneyers), email me (jon at cloudinary.com), or if you're lucky, find me on gitter (https://gitter.im/FLIF-hub/FLIF).

Note that FUIF will not be updated – we are now combining FUIF with Google's Pik and the result will be called JPEG XL (https://jpeg.org/jpegxl/).

**Comment by brunoais** [comment]
@jonsneyers 
> Note that FUIF will not be updated – we are now combining FUIF with Google's Pik and the result will be called JPEG XL (https://jpeg.org/jpegxl/).

May you please update the top of the README with that same paragraph?
Updating in both FUIF and FLIF projects would be great.

**Comment by jonsneyers** [comment]
Done.
